import { VerticalBox , ScrollView, ProgressIndicator , GridBox, HorizontalBox} from "std-widgets.slint";
import { Tile } from "tile.slint";
import { Colors, ProgBox } from "colors.slint";

export struct CPUInfo {
    brand: string,
    name: string,
    usage: int,
    freq: int
}

export global CPUAdapter {
    in property <[CPUInfo]> cpus;
}


export component CPU inherits Tile {
    in property <[CPUInfo]> cpus <=> CPUAdapter.cpus;
        VerticalLayout {
            padding: 10px;
            Text{ text: "CPU: " + cpus[0].brand; font-weight: 600; }
            ScrollView { 
                padding: 5px;
                VerticalLayout {
                    for cpu in cpus : ProgBox {
                        name: cpu.name;
                        usage: cpu.usage;
                    }
                }
            }
        }
    
} 