import { HorizontalBox , VerticalBox} from "std-widgets.slint";
import { ProgressIndicator , ScrollView} from "std-widgets.slint";
import { Tile } from "tile.slint";
import { ProgBox } from "colors.slint";

export struct SystemInformation {
    sysname: string,
    syskernel: string,
    osver: string,
    hostname: string,
    uptime: string,
    used_mem: float,
    used_swap: float
}

export global InfoAdapter {
    in property <SystemInformation> info;
}

export component System inherits Tile {
    in property <SystemInformation> info <=> InfoAdapter.info;
    VerticalLayout { 
        padding: 10px;
        Text{ text: "System Information"; font-weight: 600; }
        Rectangle {
            VerticalLayout {
                padding: 5px;
                Text{ text: "System Name: " + info.sysname; }
                Text{ text: "Kernel Version: " + info.syskernel; }
                Text{ text: "OS Version: " + info.osver; }
                Text{ text: "Hostname: " + info.hostname; }
                Text{ text: "Uptime: " + info.uptime; }
                ProgBox { name: "Memory"; usage: info.used_mem; }
                ProgBox { name: "Swap"; usage: info.used_swap; }
            }
        }
    }
}