import { GroupBox, HorizontalBox } from "std-widgets.slint";

export struct NetworkInterface {
    name: string,
    received: int,
    transmitted: int
}

export global NetworkAdapter {
    in property <[NetworkInterface]> interfaces;
}

component Interface {
    in property <string> name;
    in property <int> rec;
    in property <int> trans;
    padding: 5pt;
    HorizontalLayout {
        Text{ text: "\{root.name}: \{root.rec}/\{root.trans}B"; }
    }
}

export component Network {
    in property <[NetworkInterface]> interfaces <=> NetworkAdapter.interfaces;
    HorizontalBox {
        alignment: LayoutAlignment.start;
        Text { text: "Network:"; font-weight: 600; }
        for interface in interfaces : Interface {
            name: interface.name;
            rec: interface.received;
            trans: interface.transmitted;
        }
    }
}