import { StandardTableView,ScrollView} from "std-widgets.slint";
import { Tile } from "tile.slint";

export global ProcessesAdapter {
    callback sort_ascending(int);
    callback sort_descending(int);
    in property <[[StandardListViewItem]]> processes;
}
export component Processes inherits Tile {
    in property <[[StandardListViewItem]]> processes <=> ProcessesAdapter.processes;
    VerticalLayout {
        padding: 10px;
        Text {text: "Processes"; font-weight: 600;}
        StandardTableView {
            columns: [
                { title: "PID"},
                { title: "USER"},
                { title: "RES"},
                { title: "SHR"},
                { title: "STATUS"},
                { title: "%CPU"},
                { title: "%MEM"},
                { title: "Read"},
                { title: "Write"},
                { title: "TIME"},
                { title: "COMMAND"},
            ];
            rows: root.processes; 
            sort-ascending(index) => {
                ProcessesAdapter.sort_ascending(index);
            }
            sort-descending(index) => {
                ProcessesAdapter.sort-descending(index);
            }
        }
    }
}