import { StandardTableView } from "std-widgets.slint";

export struct ProcessModel {
    pid: string,
    user: string,
    virt: string,
    status: string,
    cpu: string,
    mem: string,
    time: string,
    command: string,
}
export component ProcessList {
    in property <[ProcessModel]> processes;
    width: 230px;
    height: 200px;
    StandardTableView {
        width: 230px;
        height: 200px;
        columns: [
            { title: "Header 1" },
            { title: "Header 2" },
        ];
        rows: [
            [
                { text: "Item 1" }, { text: "Item 2" },
            ],
            [
                { text: "Item 1" }, { text: "Item 2" },
            ],
            [
                { text: "Item 1" }, { text: "Item 2" },
            ]
        ];
    }

}