import { StandardTableView } from "std-widgets.slint";

export global ProcessesAdapter {
    callback sort_ascending(int);
    callback sort_descending(int);
    in property <[[StandardListViewItem]]> processes :[
        [{text: "Item1"},{text: "Item1"},{text: "Item1"},{text: "Item1"},{text: "Item1"},{text: "Item1"},{text: "Item1"},{text: "Item1"}],
        [{text: "Item1"},{text: "Item1"},{text: "Item1"},{text: "Item1"},{text: "Item1"},{text: "Item1"},{text: "Item1"},{text: "Item1"}],
        [{text: "Item1"},{text: "Item1"},{text: "Item1"},{text: "Item1"},{text: "Item1"},{text: "Item1"},{text: "Item1"},{text: "Item1"}],
        [{text: "Item1"},{text: "Item1"},{text: "Item1"},{text: "Item1"},{text: "Item1"},{text: "Item1"},{text: "Item1"},{text: "Item1"}],
        [{text: "Item1"},{text: "Item1"},{text: "Item1"},{text: "Item1"},{text: "Item1"},{text: "Item1"},{text: "Item1"},{text: "Item1"}],
        [{text: "Item1"},{text: "Item1"},{text: "Item1"},{text: "Item1"},{text: "Item1"},{text: "Item1"},{text: "Item1"},{text: "Item1"}],
        [{text: "Item1"},{text: "Item1"},{text: "Item1"},{text: "Item1"},{text: "Item1"},{text: "Item1"},{text: "Item1"},{text: "Item1"}],
        [{text: "Item1"},{text: "Item1"},{text: "Item1"},{text: "Item1"},{text: "Item1"},{text: "Item1"},{text: "Item1"},{text: "Item1"}],
        [{text: "Item1"},{text: "Item1"},{text: "Item1"},{text: "Item1"},{text: "Item1"},{text: "Item1"},{text: "Item1"},{text: "Item1"}],
        [{text: "Item1"},{text: "Item1"},{text: "Item1"},{text: "Item1"},{text: "Item1"},{text: "Item1"},{text: "Item1"},{text: "Item1"}]
    ];
}
export component Processes {
    in property <[[StandardListViewItem]]> processes <=> ProcessesAdapter.processes;
    
    VerticalLayout {
        Text {text: "Processes:"; font-weight: 600;}
        StandardTableView {
            width: 100%;
            height: 100%;
            columns: [
                { title: "PID"},
                { title: "USER"},
                { title: "VIRT"},
                { title: "STATUS"},
                { title: "%CPU"},
                { title: "%MEM"},
                { title: "TIME"},
                { title: "COMMAND"},
            ];
            rows: root.processes; 
            sort-ascending(index) => {
                ProcessesAdapter.sort_ascending(index);
            }

            sort-descending(index) => {
                ProcessesAdapter.sort-descending(index);
            }
        }
    }
}