[package]
name = "rustop"
version = "0.1.0"
authors = ["leonardo"]
edition = "2021"
build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
slint = "1.0"
sysinfo = "0.29.9"

[build-dependencies]
slint-build = "1.0"
