import {Button, VerticalBox, StandardTableView } from "std-widgets.slint";
import {Processes, ProcessesAdapter} from "components/processes.slint";
import {Network, NetworkAdapter, NetworkInterface} from "components/network.slint";
import {IO, IOAdapter, DiskIO} from "components/io.slint";
export {ProcessesAdapter, NetworkAdapter, NetworkInterface, IOAdapter, DiskIO}
export component MainWindow inherits Window {
    width: 1400px;
    height: 900px;
    title: "Rustop";
    VerticalLayout {
        Processes {
            width: 100%;
            height: 30%;
        }
        Network {
            width: 100%;
            height: 10%;
        }
        IO {
            width: 100%;
            height: 50%;
        }
    }   
}