import { Button, VerticalBox, StandardTableView } from "std-widgets.slint";
import {Processes, ProcessesAdapter} from "components/processes.slint";
import {Network, NetworkAdapter, NetworkInterface} from "components/network.slint";
export {ProcessesAdapter, NetworkAdapter, NetworkInterface}
export component MainWindow inherits Window {
    width: 1400px;
    height: 900px;
    title: "Rustop";
    VerticalLayout {
        Processes {
            width: 100%;
            height: 40%;
        }
        Network {
            width: 100%;
            height: 10%;
        }
    }   
}